import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("nteflix.csv")

df = df.dropna(subset=['rating', 'release_year', 'country'])
type_counts = df['type'].value_counts()
plt.figure(figsize=(6, 4))
plt.bar(type_counts.index, type_counts.values, color=['blue', 'orange'])
plt.title("no of movies vs tv show")
plt.xlabel("Type")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig('movie vs tv show.png')
rating_counts = df['rating'].value_counts()
plt.figure(figsize=(10, 6))
plt.pie(rating_counts.values, labels=rating_counts.index, autopct='%1.1f%%', startangle=90)
plt.title("percentage of content rating")
plt.tight_layout()
plt.savefig('content rating.png')
movie_df = df[df['type'] == 'Movie'].copy()
movie_df = movie_df.dropna(subset=['duration'])
movie_df['duration_int'] = movie_df['duration'].str.replace(' min', '').astype(int)
plt.figure(figsize=(10, 6))
plt.hist(movie_df['duration_int'], bins=20, color='green', edgecolor='black')
plt.title("Distribution of Movie Durations")
plt.xlabel("Duration (minutes)")
plt.ylabel("number of Movies")
plt.tight_layout()
plt.show()
plt.savefig('movie duration distribution.png')
release_counts = df['release_year'].value_counts().sort_index()
plt.figure(figsize=(12, 6))

plt.scatter(release_counts.index, release_counts.values, color='red')
plt.title("release year vs no of show")
plt.xlabel("Release Year")
plt.ylabel("Number of Shows")
plt.tight_layout()
plt.savefig('release year vs no of show.png')
country_counts = df['country'].value_counts().head(10)
plt.figure(figsize=(10, 6))
plt.barh(country_counts.index, country_counts.values, color='purple')
plt.title("Top 10 Countries by Number of Shows")
plt.xlabel("Number of Shows")
plt.ylabel("Country")
plt.tight_layout()
plt.savefig('top 10 countries by number of shows.png')
plt.show()
content_by_year = df.groupby('release_year')['type'].value_counts().unstack().fillna(0)  
fig, ax = plt.subplots(1,2, figsize=(12, 6))
ax[0].plot(content_by_year.index, content_by_year['Movie'], label='Movies', color='blue')
ax[0].set_title("Number of Movies Released Over the Years")
ax[0].set_xlabel("Release Year")
ax[0].set_ylabel("Number of Movies")
ax[1].plot(content_by_year.index, content_by_year['TV Show'], label='TV Shows', color='orange')
ax[1].set_title("Number of TV Shows Released Over the Years")
ax[1].set_xlabel("Release Year")
ax[1].set_ylabel("Number of TV Shows")
plt.tight_layout()
plt.savefig('movies vs tv shows over the years.png')