import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("nteflix.csv")

df = df.dropna(subset=['rating', 'release_year', 'country'])
type_counts = df['type'].value_counts()
plt.figure(figsize=(6, 4))
plt.bar(type_counts.index, type_counts.values, color=['blue', 'orange'])
plt.title("no of movies vs tv show")
plt.xlabel("Type")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig('movie vs tv show.png')
rating_counts = df['rating'].value_counts()
plt.figure(figsize=(10, 6))
plt.pie(rating_counts.values, labels=rating_counts.index, autopct='%1.1f%%', startangle=90)
plt.title("percentage of content rating")
plt.tight_layout()
plt.savefig('content rating.png')
movie_df = df[df['type'] == 'Movie'].copy()
movie_df = movie_df.dropna(subset=['duration'])
movie_df['duration_int'] = movie_df['duration'].str.replace(' min', '').astype(int)
plt.figure(figsize=(10, 6))
plt.hist(movie_df['duration_int'], bins=20, color='green', edgecolor='black')
plt.title("Distribution of Movie Durations")
plt.xlabel("Duration (minutes)")
plt.ylabel("number of Movies")
plt.tight_layout()
plt.savefig('movie duration distribution.png')
